[package]
name = "oclif_command"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
oclif_macro = { path = "../oclif_macro" }
