[package]
name = "oclif"
version = "0.0.1"
description = "Rust Open CLI Framework (based on oclif.io)"
license = "MIT"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
