[package]
name = "oclif_derive"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.69" }
quote = "1.0.9"
proc-macro2 = "1.0.26"
