[package]
name = "oclif"
version = "0.1.0"
description = "Rust Open CLI Framework (based on oclif.io)"
license = "MIT"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"

[dependencies]
oclif_macro = { path = "../oclif_macro" }
structopt = "0.2.18"
