[package]
name = "oclif_structopt"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
structopt = "0.2.18"
